# Google API Key Detector
name = "Google API Detector"

[[step]]
type = "filter"
pattern = 'AIza[0-9A-Za-z\\-_]{35}'
action = "keep_line"

[[step]]
type = "substitute"
pattern = '^(.*)$'
replacement = '[GOOGLE API KEY] $1'
