# Elasticsearch Log Processor
name = "Elasticsearch Processor"

[[step]]
type = "filter"
pattern = '\[WARN\]|\[ERROR\]|\[FATAL\]'
action = "keep_line"

[[step]]
type = "substitute"
pattern = '\[(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}),\d+\]'
replacement = '[$1]'
