# Redis Log Processor
name = "Redis Processor"

[[step]]
type = "filter"
pattern = '\*\s+(\d+)\s+clients'
action = "keep_line"

[[step]]
type = "filter"
pattern = '#\s+(WARNING|Client)\s+'
action = "keep_line"
